name: Rust-WebAssembly

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install Node.js dependencies
        run: npm install
      - name: Build release
        run: npm run build
      - name: Run tests
        run: cargo test --verbose
